## Imports

In [5]:
# Import pandas for data manipulation and os for file path handling

import pandas as pd
import os

## File Paths

In [6]:
# Define each file name and its date format
# 2021 and 2022 use short year format (YY-MM-DD), rest use full ISO format

files = {
    "2021": ("2021_Data.csv", "%y-%m-%d"),
    "2022": ("2022_Data.csv", "%y-%m-%d"),
    "2023": ("2023_Data.csv", "mixed"),
    "2024": ("2024_Data.csv", "mixed"),
    "2025": ("2025_Data.csv", "mixed"),
    "2026": ("2026_Data_30th June.csv", "mixed"),
}

## Displaying First 3 Rows for each year before Cleaning

In [7]:
# Quick sanity check — display first 3 rows of each file
# to confirm files loaded correctly before full processing

for year, (path, fmt) in files.items():
    df = pd.read_csv(path, nrows=3)
    print(f"\n=== {year} ===")
    display(df.head(3))

=== 2021 ===

,_id,OCCUPANCY_DATE,ORGANIZATION_ID,ORGANIZATION_NAME,SHELTER_ID,SHELTER_GROUP,LOCATION_ID,LOCATION_NAME,LOCATION_ADDRESS,LOCATION_POSTAL_CODE,...,OCCUPIED_BEDS,UNOCCUPIED_BEDS,UNAVAILABLE_BEDS,CAPACITY_ACTUAL_ROOM,CAPACITY_FUNDING_ROOM,OCCUPIED_ROOMS,UNOCCUPIED_ROOMS,UNAVAILABLE_ROOMS,OCCUPANCY_RATE_BEDS,OCCUPANCY_RATE_ROOMS
0,1,21-01-01,24,COSTI Immigrant Services,40,COSTI Reception Centre,1103,COSTI/City North York West Hotel Program,1677 Wilson Ave,M3L 1A5,...,NaN,NaN,NaN,29,58,26,3,29,NaN,89.66
1,2,21-01-01,24,COSTI Immigrant Services,40,COSTI Reception Centre,1103,COSTI/City North York West Hotel Program,1677 Wilson Ave,M3L 1A5,...,NaN,NaN,NaN,3,0,3,0,0,NaN,100.00
2,3,21-01-01,24,COSTI Immigrant Services,40,COSTI Reception Centre,1103,COSTI/City North York West Hotel Program,1677 Wilson Ave,M3L 1A5,...,NaN,NaN,NaN,28,0,23,5,0,NaN,82.14

=== 2022 ===

,_id,OCCUPANCY_DATE,ORGANIZATION_ID,ORGANIZATION_NAME,SHELTER_ID,SHELTER_GROUP,LOCATION_ID,LOCATION_NAME,LOCATION_ADDRESS,LOCATION_POSTAL_CODE,...,OCCUPIED_BEDS,UNOCCUPIED_BEDS,UNAVAILABLE_BEDS,CAPACITY_ACTUAL_ROOM,CAPACITY_FUNDING_ROOM,OCCUPIED_ROOMS,UNOCCUPIED_ROOMS,UNAVAILABLE_ROOMS,OCCUPANCY_RATE_BEDS,OCCUPANCY_RATE_ROOMS
0,1,22-01-01,24,COSTI Immigrant Services,40,COSTI Reception Centre,1103,SSHA North York West Hotel Program,1677 Wilson Ave,M3L 1A5,...,NaN,NaN,NaN,48,55,48,0,7,NaN,100
1,2,22-01-01,24,COSTI Immigrant Services,40,COSTI Reception Centre,1103,SSHA North York West Hotel Program,1677 Wilson Ave,M3L 1A5,...,NaN,NaN,NaN,9,15,9,0,6,NaN,100
2,3,22-01-01,24,COSTI Immigrant Services,40,COSTI Reception Centre,1103,SSHA North York West Hotel Program,1677 Wilson Ave,M3L 1A5,...,NaN,NaN,NaN,18,29,18,0,11,NaN,100

=== 2023 ===

,_id,OCCUPANCY_DATE,ORGANIZATION_ID,ORGANIZATION_NAME,SHELTER_ID,SHELTER_GROUP,LOCATION_ID,LOCATION_NAME,LOCATION_ADDRESS,LOCATION_POSTAL_CODE,...,OCCUPIED_BEDS,UNOCCUPIED_BEDS,UNAVAILABLE_BEDS,CAPACITY_ACTUAL_ROOM,CAPACITY_FUNDING_ROOM,OCCUPIED_ROOMS,UNOCCUPIED_ROOMS,UNAVAILABLE_ROOMS,OCCUPANCY_RATE_BEDS,OCCUPANCY_RATE_ROOMS
0,1,2023-01-01T00:00:00,24,COSTI Immigrant Services,40,COSTI Reception Centre,1320,COSTI Hotel Program Dixon,640 Dixon Rd.,M9W 1J1,...,NaN,NaN,NaN,148.0,150.0,148.0,0.0,2.0,NaN,100.0
1,2,2023-01-01T00:00:00,24,COSTI Immigrant Services,40,COSTI Reception Centre,1320,COSTI Hotel Program Dixon,640 Dixon Rd.,M9W 1J1,...,NaN,NaN,NaN,56.0,56.0,56.0,0.0,0.0,NaN,100.0
2,3,2023-01-01T00:00:00,24,COSTI Immigrant Services,40,COSTI Reception Centre,1051,COSTI Reception Centre,100 Lippincott St,M5S 2P1,...,8.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,100.0,NaN

=== 2024 ===

,_id,OCCUPANCY_DATE,ORGANIZATION_ID,ORGANIZATION_NAME,SHELTER_ID,SHELTER_GROUP,LOCATION_ID,LOCATION_NAME,LOCATION_ADDRESS,LOCATION_POSTAL_CODE,...,OCCUPIED_BEDS,UNOCCUPIED_BEDS,UNAVAILABLE_BEDS,CAPACITY_ACTUAL_ROOM,CAPACITY_FUNDING_ROOM,OCCUPIED_ROOMS,UNOCCUPIED_ROOMS,UNAVAILABLE_ROOMS,OCCUPANCY_RATE_BEDS,OCCUPANCY_RATE_ROOMS
0,1,2024-01-01,24,COSTI Immigrant Services,40,COSTI Reception Centre,1320,COSTI Hotel Program Dixon,640 Dixon Rd.,M9W 1J1,...,NaN,NaN,NaN,149.0,150.0,149.0,0.0,1.0,NaN,100.0
1,2,2024-01-01,24,COSTI Immigrant Services,40,COSTI Reception Centre,1320,COSTI Hotel Program Dixon,640 Dixon Rd.,M9W 1J1,...,NaN,NaN,NaN,57.0,57.0,57.0,0.0,0.0,NaN,100.0
2,3,2024-01-01,24,COSTI Immigrant Services,40,COSTI Reception Centre,1051,COSTI Reception Centre,100 Lippincott St,M5S 2P1,...,8.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,100.0,NaN

=== 2025 ===

,_id,OCCUPANCY_DATE,ORGANIZATION_ID,ORGANIZATION_NAME,SHELTER_ID,SHELTER_GROUP,LOCATION_ID,LOCATION_NAME,LOCATION_ADDRESS,LOCATION_POSTAL_CODE,...,OCCUPIED_BEDS,UNOCCUPIED_BEDS,UNAVAILABLE_BEDS,CAPACITY_ACTUAL_ROOM,CAPACITY_FUNDING_ROOM,OCCUPIED_ROOMS,UNOCCUPIED_ROOMS,UNAVAILABLE_ROOMS,OCCUPANCY_RATE_BEDS,OCCUPANCY_RATE_ROOMS
0,1,2025-01-01,5,The Scott Mission Inc.,8,Scott Mission Men's Ministry,1300,The Scott Mission - Kensington location,346 Spadina Ave.,M5T 1J5,...,71,0,0,NaN,NaN,NaN,NaN,NaN,100,NaN
1,2,2025-01-01,15,Homes First Society,24,HFS - Scarborough Shelter,1153,HFS Willowdale Centre,5800 Yonge St,M2M 3T3,...,6,0,0,NaN,NaN,NaN,NaN,NaN,100,NaN
2,3,2025-01-01,35,Margaret's Housing and Community Support Services,67,Margaret's Toronto East Drop-In,1118,Margaret's 21 Park Rd Respite,21 Park Rd,M4W 2N1,...,30,0,0,NaN,NaN,NaN,NaN,NaN,100,NaN

=== 2026 ===

,_id,OCCUPANCY_DATE,ORGANIZATION_ID,ORGANIZATION_NAME,SHELTER_ID,SHELTER_GROUP,LOCATION_ID,LOCATION_NAME,LOCATION_ADDRESS,LOCATION_POSTAL_CODE,...,OCCUPIED_BEDS,UNOCCUPIED_BEDS,UNAVAILABLE_BEDS,CAPACITY_ACTUAL_ROOM,CAPACITY_FUNDING_ROOM,OCCUPIED_ROOMS,UNOCCUPIED_ROOMS,UNAVAILABLE_ROOMS,OCCUPANCY_RATE_BEDS,OCCUPANCY_RATE_ROOMS
0,1,2026-01-01,24,COSTI Immigrant Services,40,COSTI Reception Centre,1320,COSTI Hotel Program Dixon,640 Dixon Rd.,M9W 1J1,...,NaN,NaN,NaN,149.0,149.0,132.0,17.0,0.0,NaN,88.59
1,2,2026-01-01,24,COSTI Immigrant Services,40,COSTI Reception Centre,1320,COSTI Hotel Program Dixon,640 Dixon Rd.,M9W 1J1,...,NaN,NaN,NaN,57.0,57.0,57.0,0.0,0.0,NaN,100.00
2,3,2026-01-01,24,COSTI Immigrant Services,40,COSTI Reception Centre,1051,COSTI Reception Centre,100 Lippincott St,M5S 2P1,...,7.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,87.5,NaN

## Loading and Parsing Each file

In [8]:
# Load all 6 files completely, parse dates with correct format per year
# Normalize removes the time component and keeps date only

dfs = []
for year, (path, fmt) in files.items():
    df = pd.read_csv(path)
    df['OCCUPANCY_DATE'] = pd.to_datetime(df['OCCUPANCY_DATE'], format=fmt)
    df['OCCUPANCY_DATE'] = df['OCCUPANCY_DATE'].dt.normalize()
    print(f"{year}: {len(df):,} rows")
    dfs.append(df)

2021: 50,944 rows
2022: 49,478 rows
2023: 48,345 rows
2024: 48,794 rows
2025: 51,543 rows
2026: 28,251 rows

## Concatenate and deduplicate

In [9]:
# Stack all 6 dataframes into one and remove any exact duplicate rows

combined = pd.concat(dfs, ignore_index=True)
before = len(combined)
combined = combined.drop_duplicates()
print(f"Before dedup : {before:,}")
print(f"After dedup  : {len(combined):,}")
print(f"Removed      : {before - len(combined):,}")

Before dedup : 277,355
After dedup  : 274,487
Removed      : 2,868

## Validate date range

In [10]:
# Confirm all dates fall within the expected 2021-2026 window
# If any date is outside this range the script will raise an error

min_date = combined['OCCUPANCY_DATE'].min()
max_date = combined['OCCUPANCY_DATE'].max()
print(f"Date range: {min_date.date()} → {max_date.date()}")
assert min_date.year == 2021
assert max_date.year == 2026
print("Date range check: PASSED")

Date range: 2021-01-01 → 2026-06-30
Date range check: PASSED

## Adding Derived Fields

In [12]:
# CAPACITY_GAP: how many funded beds are offline each night per program
# AT_RISK_FLAG: True if program is overcrowded (>90%) or underutilized (<40%)

combined['CAPACITY_GAP'] = (
    combined['CAPACITY_FUNDING_BED'] - combined['CAPACITY_ACTUAL_BED'])

combined['AT_RISK_FLAG'] = (
    (combined['OCCUPANCY_RATE_BEDS'] > 90) |
    (combined['OCCUPANCY_RATE_BEDS'] < 40))

print(f"CAPACITY_GAP avg : {combined['CAPACITY_GAP'].mean():.2f} beds")
print(f"AT_RISK_FLAG True: {combined['AT_RISK_FLAG'].sum():,} rows")

CAPACITY_GAP avg : 1.78 beds
AT_RISK_FLAG True: 165,838 rows

## Exporting the Clean CSV

In [13]:
# Save the final cleaned dataset to the current working directory
# This file will be used in Phase 2 to load into MySQL

combined.to_csv("shelter_clean.csv", index=False)
print(f"Saved: shelter_clean.csv")
print(f"Rows : {len(combined):,}")
print(f"Cols : {len(combined.columns)}")
print("Phase 1 complete.")

Saved: shelter_clean.csv
Rows : 274,487
Cols : 34
Phase 1 complete.

In [14]:
import os
print(os.getcwd())

C:\Users\admin\anaconda_projects\6e2bb88d-71d0-4c09-bd93-1da1a85040ca

In [15]:
import os
# Lists all CSV files visible to Jupyter right now
for f in os.listdir():
    if f.endswith('.csv'):
        print(f)

2021_Data.csv
2022_Data.csv
2023_Data.csv
2024_Data.csv
2025_Data.csv
2026_Data_30th June.csv
shelter_clean.csv